language: C
sudo: false

branches:
  only:
  - master
  - tss
  - dpdk

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-get install -y libnuma-dev
  - sudo apt-get install -y linux-modules-4.15.0-1028-gcp linux-headers-$(uname -r)

script:
  - ./boot.sh
  - make
