language: C
sudo: false

branches:
  only:
  - master
  - tss
  - dpdk

compiler:
  - gcc

os:
  - linux

script:
  - export RTE_SDK=lib/dpdk-stable-19.11.3
  - export RTE_TARGET=x86_64-native-linuxapp-gcc
  - cd lib/dpdk-stable-19.11.3
  - make install T=x86_64-native-linuxapp-gcc -j 10
  - cd ../..
  - make
